"""Core package for the Forgetting Cure experiment."""

from .config import Config
from .matrix import (
    Matrix,
    add,
    argmax_row,
    clip,
    col_slice,
    deep_copy,
    flatten,
    from_flat,
    he_init,
    hstack,
    matmul,
    multiply,
    ones,
    random_matrix,
    random_normal,
    relu,
    relu_derivative,
    row_slice,
    scalar_add,
    scalar_mul,
    shape,
    softmax,
    subtract,
    sum_cols,
    sum_rows,
    to_one_hot,
    transpose,
    vstack,
    zeros,
)
from .metrics import MetricsTracker
from .network import Network, Strategy

__all__ = [
    # config
    "Config",
    # matrix
    "Matrix",
    "add",
    "argmax_row",
    "clip",
    "col_slice",
    "deep_copy",
    "flatten",
    "from_flat",
    "he_init",
    "hstack",
    "matmul",
    "multiply",
    "ones",
    "random_matrix",
    "random_normal",
    "relu",
    "relu_derivative",
    "row_slice",
    "scalar_add",
    "scalar_mul",
    "shape",
    "softmax",
    "subtract",
    "sum_cols",
    "sum_rows",
    "to_one_hot",
    "transpose",
    "vstack",
    "zeros",
    # metrics
    "MetricsTracker",
    # network
    "Network",
    "Strategy",
]
