"""Anton handoff protocol — bridge between Voronoi (science) and Anton/MVCHA (engineering).

When Voronoi discovers a root cause or produces a fix specification,
this module creates structured GitHub issues or Beads tasks that
Anton (MVCHA) can pick up and execute.
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from voronoi.beads import run_cmd as _run_cmd


@dataclass
class FixSpec:
    """A structured fix specification produced by Voronoi for Anton."""
    title: str
    finding_id: str              # Beads ID of the source finding
    root_cause: str              # What was discovered
    fix_description: str         # What needs to be done
    expected_improvement: str    # Predicted effect with CI
    files_to_change: list[str] = field(default_factory=list)
    repo: Optional[str] = None  # GitHub repo (owner/repo)
    priority: int = 1
    validation_criteria: str = ""  # How to verify the fix worked

    def to_github_body(self) -> str:
        """Format as a GitHub issue body."""
        lines = [
            f"## Root Cause (Voronoi Finding `{self.finding_id}`)",
            "",
            self.root_cause,
            "",
            "## Fix Specification",
            "",
            self.fix_description,
            "",
        ]
        if self.files_to_change:
            lines.append("### Files to Change")
            lines.append("")
            for f in self.files_to_change:
                lines.append(f"- `{f}`")
            lines.append("")
        lines.extend([
            "## Expected Improvement",
            "",
            self.expected_improvement,
            "",
            "## Validation Criteria",
            "",
            self.validation_criteria or "Re-run the original experiment and verify improvement is within predicted CI.",
            "",
            "---",
            f"_Generated by Voronoi science engine. Source: finding `{self.finding_id}`_",
            "_Label: `voronoi-spec`_",
        ])
        return "\n".join(lines)

    def to_beads_description(self) -> str:
        """Format as a Beads task description."""
        lines = [
            f"Root cause: {self.root_cause}",
            f"Fix: {self.fix_description}",
            f"Expected: {self.expected_improvement}",
        ]
        if self.files_to_change:
            lines.append(f"Files: {', '.join(self.files_to_change)}")
        if self.validation_criteria:
            lines.append(f"Validate: {self.validation_criteria}")
        lines.append(f"Source: {self.finding_id}")
        return "\n".join(lines)


# _run_cmd imported from voronoi.beads


class AntonHandoff:
    """Manages handoff of actionable tasks from Voronoi to Anton/MVCHA."""

    def __init__(self, project_dir: str | Path):
        self.project_dir = str(project_dir)

    def create_beads_task(self, spec: FixSpec) -> tuple[bool, str]:
        """Create a Beads task for Anton to pick up.

        Returns (success, message).
        """
        code, output = _run_cmd(
            [
                "bd", "create", f"[ANTON] {spec.title}",
                "-t", "task",
                "-p", str(spec.priority),
                f"--description={spec.to_beads_description()}",
                "--json",
            ],
            cwd=self.project_dir,
        )

        if code != 0:
            return False, f"Failed to create task: {output}"

        try:
            result = json.loads(output)
            task_id = result.get("id", "")
        except (json.JSONDecodeError, ValueError):
            task_id = ""

        if not task_id:
            return True, f"Created Anton task (unknown id): {spec.title}"

        # Add metadata notes
        _run_cmd(
            ["bd", "update", task_id, "--notes",
             f"HANDOFF:anton | SOURCE_FINDING:{spec.finding_id} | CREATED:{time.time():.0f}"],
            cwd=self.project_dir,
        )

        return True, f"Created Anton task `{task_id}`: {spec.title}"

    def create_github_issue(self, spec: FixSpec) -> tuple[bool, str]:
        """Create a GitHub issue labeled voronoi-spec for Anton.

        Requires `gh` CLI to be installed and authenticated.
        """
        if not spec.repo:
            return False, "No repo specified in fix spec"

        code, output = _run_cmd(
            [
                "gh", "issue", "create",
                "--repo", spec.repo,
                "--title", f"[Voronoi] {spec.title}",
                "--body", spec.to_github_body(),
                "--label", "voronoi-spec",
            ],
            cwd=self.project_dir,
        )

        if code != 0:
            return False, f"Failed to create GitHub issue: {output}"

        return True, f"Created GitHub issue: {output}"

    def create_validation_task(self, spec: FixSpec, fix_task_id: str) -> tuple[bool, str]:
        """Create a validation task that runs AFTER Anton's fix is merged.

        This is Voronoi's post-fix verification — re-run the original experiment
        to confirm the fix actually worked.
        """
        title = f"[VALIDATE] Verify fix for {spec.title}"
        description = (
            f"Re-run the experiment from finding {spec.finding_id} to verify "
            f"Anton's fix ({fix_task_id}) achieved the expected improvement.\n\n"
            f"Expected: {spec.expected_improvement}\n"
            f"Validation: {spec.validation_criteria}"
        )

        code, output = _run_cmd(
            [
                "bd", "create", title,
                "-t", "task",
                "-p", str(spec.priority),
                f"--description={description}",
                "--json",
            ],
            cwd=self.project_dir,
        )

        if code != 0:
            return False, f"Failed to create validation task: {output}"

        try:
            result = json.loads(output)
            val_id = result.get("id", "?")
        except (json.JSONDecodeError, ValueError):
            val_id = "?"

        # Add dependency: validation blocked by fix task
        _run_cmd(
            ["bd", "dep", "add", val_id, fix_task_id],
            cwd=self.project_dir,
        )
        _run_cmd(
            ["bd", "update", val_id, "--notes",
             f"HANDOFF:voronoi-validation | FIX_TASK:{fix_task_id} | SOURCE_FINDING:{spec.finding_id}"],
            cwd=self.project_dir,
        )

        return True, f"Created validation task `{val_id}` (blocked by `{fix_task_id}`)"

    def format_handoff_notification(self, spec: FixSpec, task_id: str) -> str:
        """Format a Telegram notification about the handoff."""
        return (
            f"🤝 *Handoff to Anton*\n\n"
            f"Finding: `{spec.finding_id}`\n"
            f"Root cause: {spec.root_cause[:100]}\n"
            f"Fix: {spec.fix_description[:100]}\n"
            f"Expected: {spec.expected_improvement}\n\n"
            f"Task: `{task_id}`\n"
            f"_Anton will pick this up and open a PR._"
        )
